baseURL = "https://snapcrafters.org"
languageCode = "en-gb"
title = "Snapcrafters"
sectionPagesMenu = "main"

[params]
author = "Snapcrafters Community"
description = "A community of volunteers maintaining unofficial snap packages."
favicon = "https://avatars.githubusercontent.com/u/29598503?s=128"

[markup.goldmark.renderer]
unsafe = true
